#!/bin/bash

# Script d'ajout/mise à jour des chaînes à traduire.
#
# @license http://www.opensource.org/licenses/GPL-3.0 GNU General Public License, version 3 (GPL-3.0)
# @link http://loamok.org/projects/backup
#
# @package Backup
# @version v0.1_beta_1 préversion 1 béta 1
#
# @author Huby Franck <franck.huby@loamok.org>
#

. config.conf


grep -r '_(' ../* | cut -d ':' -f 1  | grep '../' | grep '.php' | sort -u >> ./fileSourcesList
cat fileSourcesList | sort -u >> fileSourcesListNew
mv fileSourcesListNew fileSourcesList

xgettext -f fileSourcesList -o backup.pot -j -F -n \
    --from-code="$codeName" -d backup \
    --copyright-holder=loamok.org \
    --package-name="Loamok Backup : https://loamok.org/projects/backup" \
    --package-version=0.1_beta_1 \
    --msgid-bugs-address=https://loamok.org/projects/backup \
    --foreign-user 

patch -p0 backup.pot < potBase.patch
sed -i 's/^\"POT-Creation-Date: \(.*\)\\n\"$/\"POT-Creation-Date: 2013-05-25 11:10+0200\\n\"\n\"POT-Revision-Date: \1\\n\"/' backup.pot
sed -i 's/^\"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n\"/\"Last-Translator: '"$translator"'\\n\"/' backup.pot
sed -i 's/\"Language-Team: LANGUAGE <LL@li.org>\\n\"/\"Language-Team: NONE\\n\"/' backup.pot
sed -i 's/\"Language: \\n\"/\"Language: FRENCH\\n\"/' backup.pot

for lang in "${langs[@]}"
do
    baseDirname="${lang}.${codeCode}"
    if [ -f $baseDirname/LC_MESSAGES/default.po ]
    then
        msgmerge -U $baseDirname/LC_MESSAGES/default.po -i backup.pot
    else
        msginit -l $lang -o $baseDirname/LC_MESSAGES/default.po -i backup.pot
    fi
done

echo "Traduisez les fichiers de langues et lancez le script 'compileLangs'."
echo "Make translation in language files, then run the script 'compileLangs'."
exit 0
